<div class="row">
	<div class="col-md-12">
		<h1>Lista de contatos</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<button class="btn btn-default btn-md pull-right">
			<i class="fa fa-download"></i> Exportar
		</button>	
	</div>
</div>
<div class="row">
	<div class="col-md-12">			
		<br>
		<table class="table table-striped">
		<tr>
		     <th>Nome</th>
		     <th>Email</th>
		     <th>Telefone</th>
		     <th>Ações</th>
		</tr>
		
		<?php foreach ($contatos as $contato) : ?>
		 <tr>
			<td><?php echo $contato->nome ?></td>
			<td><?php echo $contato->email ?></td>
			<td><?php echo $contato->telefone ?></td>
			<td>
		        <a href="<?php echo $this->url('contatos', ['action'=>'edit', 'id' => $contato->id]); ?>">
		         	<i class="fa fa-pencil"></i> Editar 
		        </a>
		        <a href="<?php echo $this->url('contatos',['action'=>'delete', 'id' => $contato->id]); ?>">
		         	<i class="fa fa-trash-o"></i> Excluir
		        </a>
		    </td>
		 </tr>
		 <?php endforeach; ?>
		 </table>
	</div>
</div>